name: Preprocessing Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Set up Python 3.12.7
      - name: Setup Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      # Run the preprocessing script
      - name: Run preprocessing script
        working-directory: preprocessing
        run: |
          python automate_ajus-dwimantara.py

      # Commit and push preprocessed dataset
      - name: Commit and push preprocessed dataset
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"
          git add preprocessing/automate_ajus-dwimantara.py
          git diff --cached --quiet || (git commit -m "Update preprocessed dataset" && git push origin master)
